import jsPDF from 'jspdf';

interface OpportunityReportData {
  businessName: string;
  domain: string;
  city?: string;
  state?: string;
  industry?: string;
  overallScore: number;
  scores: {
    technicalSEO: number;
    onPageSEO: number;
    contentMarketing: number;
    localSEO: number;
  };
  hasBlog: boolean;
  blogPostCount?: number;
  seoIssues?: Array<{
    category: string;
    issue: string;
    severity: string;
    fix: string;
  }>;
  marketSummary?: {
    industryContext: string;
    trafficGap: string;
    revenueOpportunity: string;
    confidenceLevel: string;
  };
  strengths: Array<{
    area: string;
    score: number;
    description: string;
  }>;
  gaps: Array<{
    area: string;
    score: number;
    severity: string;
    description: string;
  }>;
  opportunities: Array<{
    title: string;
    description: string;
    impact: string;
    estimatedValue: string;
    timeline: string;
    investment: string;
    actions: string[];
  }>;
  generatedBy: string;
  generatedDate: string;
}

export async function generateOpportunityReportPDF(data: OpportunityReportData): Promise<Buffer> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Helper functions
  const checkAddPage = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - 20) {
      doc.addPage();
      yPosition = 20;
      return true;
    }
    return false;
  };

  const getScoreColor = (score: number): [number, number, number] => {
    if (score >= 85) return [16, 185, 129]; // green
    if (score >= 75) return [59, 130, 246]; // blue
    if (score >= 60) return [245, 158, 11]; // yellow
    return [239, 68, 68]; // red
  };

  // COVER PAGE
  doc.setFillColor(249, 115, 22); // orange-600
  doc.rect(0, 0, pageWidth, 60, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('Growth Opportunity', pageWidth / 2, 25, { align: 'center' });
  doc.text('Analysis', pageWidth / 2, 45, { align: 'center' });

  yPosition = 80;

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(24);
  doc.text(data.businessName, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139);
  doc.text(data.domain, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 6;

  if (data.city && data.state) {
    doc.text(`${data.city}, ${data.state}`, pageWidth / 2, yPosition, { align: 'center' });
  }

  // Overall score circle
  yPosition = 130;
  const scoreColor = getScoreColor(data.overallScore);
  doc.setFillColor(...scoreColor);
  doc.circle(pageWidth / 2, yPosition, 25, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(data.overallScore.toString(), pageWidth / 2, yPosition + 8, { align: 'center' });

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(10);
  doc.text('Overall Score', pageWidth / 2, yPosition + 40, { align: 'center' });

  // Footer
  yPosition = pageHeight - 20;
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by ${data.generatedBy} | ${data.generatedDate}`, pageWidth / 2, yPosition, { align: 'center' });

  // PAGE 2: EXECUTIVE SUMMARY
  doc.addPage();
  yPosition = 20;

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 14, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  const summaryText = `This report analyzes ${data.businessName}'s web presence and identifies specific opportunities for growth. Your overall score of ${data.overallScore}/100 indicates ${data.overallScore >= 75 ? 'strong' : data.overallScore >= 60 ? 'good' : 'significant'} potential for improvement.`;
  const splitText = doc.splitTextToSize(summaryText, pageWidth - 28);
  doc.text(splitText, 14, yPosition);
  yPosition += splitText.length * 5 + 10;

  // Score breakdown
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Performance Breakdown', 14, yPosition);
  yPosition += 8;

  const scores = [
    { label: 'Technical SEO', value: data.scores.technicalSEO },
    { label: 'On-Page SEO', value: data.scores.onPageSEO },
    { label: 'Content Marketing', value: data.scores.contentMarketing },
    { label: 'Local SEO', value: data.scores.localSEO },
  ];

  scores.forEach((score) => {
    const barWidth = 120;
    const barHeight = 8;
    const safeValue = Math.max(0, Math.min(100, score.value || 0)); // Ensure value is between 0-100
    const fillWidth = (safeValue / 100) * barWidth;
    const scoreColor = getScoreColor(safeValue);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(score.label, 14, yPosition + 6);

    doc.text(`${Math.round(safeValue)}/100`, pageWidth - 14, yPosition + 6, { align: 'right' });

    // Background bar
    doc.setFillColor(226, 232, 240);
    doc.rect(50, yPosition, barWidth, barHeight, 'F');

    // Fill bar
    doc.setFillColor(...scoreColor);
    doc.rect(50, yPosition, fillWidth, barHeight, 'F');

    yPosition += 12;
  });

  yPosition += 8;
  checkAddPage(50);

  // Market Opportunity Summary (AI-generated) - Compact
  if (data.marketSummary) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(249, 115, 22);
    doc.text('Market Opportunity', 14, yPosition);
    yPosition += 6;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);

    // Combine all three paragraphs into continuous text
    const fullSummary = `${data.marketSummary.industryContext} ${data.marketSummary.trafficGap} ${data.marketSummary.revenueOpportunity}`;
    const summaryText = doc.splitTextToSize(fullSummary, pageWidth - 28);
    doc.text(summaryText, 14, yPosition);
    yPosition += summaryText.length * 4 + 5;

    // Confidence note - inline
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'italic');
    const confidenceText = doc.splitTextToSize(`* ${data.marketSummary.confidenceLevel}`, pageWidth - 28);
    doc.text(confidenceText, 14, yPosition);
    yPosition += confidenceText.length * 3 + 8;

    checkAddPage(25);
  }

  // Key Findings - Strengths & Gaps Combined
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Key Findings', 14, yPosition);
  yPosition += 8;

  // Strengths - compact bullets
  if (data.strengths.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(16, 185, 129);
    doc.text('Strengths:', 14, yPosition);
    yPosition += 6;

    data.strengths.forEach((strength) => {
      checkAddPage(8);
      doc.setFontSize(9);
      doc.setTextColor(16, 185, 129);
      doc.setFont('helvetica', 'bold');
      doc.text('•', 16, yPosition);

      doc.setTextColor(30, 41, 59);
      doc.text(`${strength.area} (${strength.score}/100):`, 22, yPosition);
      yPosition += 4;

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      const descText = doc.splitTextToSize(strength.description, pageWidth - 30);
      doc.text(descText, 22, yPosition);
      yPosition += descText.length * 4 + 2;
    });

    yPosition += 4;
  }

  checkAddPage(25);

  // Gaps - compact bullets
  if (data.gaps.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(239, 68, 68);
    doc.text('Priority Improvements:', 14, yPosition);
    yPosition += 6;

    data.gaps.forEach((gap) => {
      checkAddPage(8);
      doc.setFontSize(9);
      const severityColor: [number, number, number] =
        gap.severity === 'Critical' ? [239, 68, 68] :
        gap.severity === 'High' ? [245, 158, 11] : [59, 130, 246];

      doc.setTextColor(...severityColor);
      doc.setFont('helvetica', 'bold');
      doc.text('•', 16, yPosition);

      doc.setTextColor(30, 41, 59);
      doc.text(`${gap.area} (${gap.score}/100):`, 22, yPosition);
      yPosition += 4;

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      const descText = doc.splitTextToSize(gap.description, pageWidth - 30);
      doc.text(descText, 22, yPosition);
      yPosition += descText.length * 4 + 2;
    });

    yPosition += 6;
  }

  // OPPORTUNITIES PAGE
  doc.addPage();
  yPosition = 20;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(249, 115, 22);
  doc.text('Growth Opportunities', 14, yPosition);
  yPosition += 10;

  data.opportunities.forEach((opp, index) => {
    checkAddPage(25);

    // Opportunity number badge
    const impactColor: [number, number, number] =
      opp.impact === 'Critical' ? [239, 68, 68] :
      opp.impact === 'High' ? [16, 185, 129] : [59, 130, 246];

    doc.setFillColor(...impactColor);
    doc.circle(16, yPosition + 3, 6, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text((index + 1).toString(), 16, yPosition + 6, { align: 'center' });

    // Title and impact on same line
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text(opp.title, 25, yPosition + 5);

    doc.setFontSize(8);
    doc.setTextColor(...impactColor);
    doc.text(`[${opp.impact} Impact]`, pageWidth - 14, yPosition + 5, { align: 'right' });

    yPosition += 12;

    // Description
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const oppDescText = doc.splitTextToSize(opp.description, pageWidth - 28);
    doc.text(oppDescText, 14, yPosition);
    yPosition += oppDescText.length * 4 + 4;

    // Actions - compact format, top 3 only
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 116, 139);
    doc.text('Key Actions:', 14, yPosition);
    yPosition += 4;

    opp.actions.slice(0, 3).forEach((action, i) => {
      checkAddPage(8);
      doc.setFontSize(8);
      doc.setTextColor(249, 115, 22);
      doc.text('•', 16, yPosition);

      doc.setTextColor(71, 85, 105);
      doc.setFont('helvetica', 'normal');
      const actionText = doc.splitTextToSize(action, pageWidth - 30);
      doc.text(actionText, 20, yPosition);
      yPosition += actionText.length * 4 + 1;
    });

    yPosition += 6;

    // Separator line
    if (index < data.opportunities.length - 1) {
      doc.setDrawColor(226, 232, 240);
      doc.line(14, yPosition, pageWidth - 14, yPosition);
      yPosition += 8;
    }
  });

  // NEXT STEPS - at bottom of opportunities page
  yPosition += 18;
  checkAddPage(35);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Next Steps', 14, yPosition);
  yPosition += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text('Schedule a complimentary consultation to discuss pricing and implementation.', 14, yPosition);
  yPosition += 8;

  // CTA Box - compact
  doc.setFillColor(254, 243, 199);
  doc.setDrawColor(251, 191, 36);
  doc.roundedRect(14, yPosition, pageWidth - 28, 20, 3, 3, 'FD');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(146, 64, 14);
  doc.text('Contact Us Today', 20, yPosition + 8);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 53, 15);
  doc.text('Email: your-email@agency.com | Phone: (555) 123-4567', 20, yPosition + 15);

  // Footer
  yPosition = pageHeight - 15;
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.setFont('helvetica', 'italic');
  const footerText = `Report prepared for ${data.businessName} on ${data.generatedDate}. Analysis based on automated SEO audit.`;
  const footerLines = doc.splitTextToSize(footerText, pageWidth - 28);
  doc.text(footerLines, pageWidth / 2, yPosition, { align: 'center' });

  // Return PDF as buffer
  return Buffer.from(doc.output('arraybuffer'));
}
